### ISSUE TITLE
CMake example for own project

### ISSUE THREAD

**Issue by mr337** [xqms/rosfmt#1]
I have been trying to add this project to my CMakeLists.txt with no luck. I have installed the ros pkg `ros-kinetic-rosfmt`.

Can you provide a sample CMakeLists.txt that shows to use this library? I think I am missing one items :D

**Comment by mr337** [comment]
Here is what I have added to my project with no success, if this helps.

CmakeLists.txt
```
find_package(rosfmt REQUIRED)

catkin_package(
   INCLUDE_DIRS include
   LIBRARIES pid rosfmt
  CATKIN_DEPENDS  rospy std_msgs sensor_msgs geometry_msgs message_generation dynamic_reconfigure angles)

include_directories(
  include
  ${catkin_INCLUDE_DIRS}
  ${GeographicLib_INCLUDE_DIRS}
  ${LIBGPX_INCLUDE_DIR}
  ${EXPAT_INCLUDE_DIRS}
  ${ROSFMT_INCLUDE_DIRS}
)

target_link_libraries(common
  ${GeographicLib_LIBRARIES}
  ${LIBGPX_LIBRARIES}
  ${EXPAT_LIBRARIES}
  ${ROSFMT_LIBRARIES}
)

common.so: undefined reference to `fmt::v5::internal::basic_data<void>::ZERO_OR_POWERS_OF_10_32'
common.so: undefined reference to `int fmt::v5::internal::char_traits<char>::format_float<double>(char*, unsigned long, char const*, int, double)'
common.so: undefined reference to `int fmt::v5::internal::char_traits<char>::format_float<long double>(char*, unsigned long, char const*, int, long double)'
common.so: undefined reference to `fmt::v5::internal::grisu2_format(double, char*, unsigned long&, char, int, bool)'
common.so: undefined reference to `fmt::v5::internal::error_handler::on_error(char const*)'
common.so: undefined reference to `fmt::v5::internal::basic_data<void>::DIGITS'
common.so: undefined reference to `char fmt::v5::internal::thousands_sep<char>(fmt::v5::locale_provider*)'
common.so: undefined reference to `fmt::v5::internal::basic_data<void>::ZERO_OR_POWERS_OF_10_64'
```
Looking at the CMakeLists of rosfmt it looks like the header files are pulled in, but not the shared lib? I'm a CMake noob so racking my brain.

**Comment by xqms** [comment]
Hi, I just added an example CMakeLists.txt to the README: https://github.com/xqms/rosfmt.

You are missing two items:
* `set(CMAKE_CXX_STANDARD 11)`
* `${catkin_LIBRARIES}` inside the `target_link_libraries` call.

**Comment by xqms** [comment]
ah, and you should specify `rosfmt` as a global catkin dependency (unless you have several targets and want to use rosfmt only for some).
That means:

`find_package(catkin REQUIRED COMPONENTS rosfmt)`

See the README for reference.

**Comment by mr337** [comment]
`find_package(catkin REQUIRED COMPONENTS rosfmt)` is what I was missing! Thanks for the example on the readme too!
