### ISSUE TITLE
Compiler Error when formatting Eigen::Matrix

### ISSUE THREAD

**Issue by invenibo** [xqms/rosfmt#2]
Hi,

I want to print an Eigen::Matrix like so:
```c++
Eigen::Matrix3d matrix;
ROSFMT_INFO("Matrix: {}", matrix);
```
The resulting compiler error is 
`error: no matching function for call to ‘fmt::v6::internal::arg_mapper<fmt::v6::basic_format_context<std::back_insert_iterator<fmt::v6::internal::buffer<char> >, char> >::map(const Eigen::Matrix<double, 2, 1>&)’
 1015 |   return arg_mapper<Context>().map(val);`

The same behavior is documented [here](https://github.com/fmtlib/fmt/issues/794).

The solution is to add `#include <fmt/ostream.h>` to `rosfmt.h`.

**Comment by xqms** [comment]
Actually I omitted `ostream.h` from `rosfmt.h` because it increases compile times significantly. If you need that functionality, you can include it in your code:

```cpp
#include <rosfmt/rosfmt.h>
#include <fmt/ostream.h> // For printing types with ostream operators
#include <fmt/ranges.h> // For printing ranges (std::vector, std::array, std::list, ...)
```

Maybe it would be a good idea to offer a `rosfmt/full.h` header that includes all functionality?

**Comment by invenibo** [comment]
Thanks for the reply, makes sense. I did not check the impact on compile time.

That's what I did, however, after I forgot to add the additional headers a couple of times I thought it would be nice to have them all in one place.

For my purposes, `rosfmt/full.h` would be an elegant solution.
